---

osp_repo: https://github.com/davidmcclure/osp-zmq.git
osp_branch: feature/dask

osp_src_dir: /opt/osp
osp_data_dir: /var/osp

osp_scheduler_host: localhost
osp_scheduler_port: 5557

osp_database: '{{ osp_data_dir }}/osp.db'
