---

- include_vars: boto.vault.yml

- name: Push the boto credentials
  template:
    src: boto.cfg.j2
    dest: /etc/boto.cfg

- name: Get server IP address
  register: server
  ec2_remote_facts:
    region: '{{ ec2_region }}'
    filters:
      instance-state-name: running
      'tag:osp': cluster-server

- name: Set the broker variable
  set_fact:
    osp_scheduler_host: '{{ server.instances[0].private_dns_name }}'
