---

- name: Create the OSP config directory
  file:
    path: /etc/osp
    group: '{{ ansible_ssh_user }}'
    owner: '{{ ansible_ssh_user }}'
    state: directory

- name: Push the OSP config
  template:
    src: '{{ item }}.yml.j2'
    dest: /etc/osp/{{ item }}.yml
  with_items:
    - osp
