---

- name: Update the source code
  git:
    repo: '{{ osp_repo }}'
    version: '{{ osp_branch }}'
    dest: '{{ osp_src_dir }}'

- name: Check if a virtualenv exists
  register: env
  stat:
    path: '{{ osp_src_dir }}/env'

# pyvenv is broken on Ubuntu 14.04.
- name: Create a Python 3 virtualenv, if necessary
  when: env.stat.isdir is not defined
  command: virtualenv --python=/usr/bin/python3.4 env
  args:
    chdir: '{{ osp_src_dir }}'

- name: Update pip
  command: env/bin/pip install --upgrade pip
  args:
    chdir: '{{ osp_src_dir }}'

- name: Install pip dependencies
  command: env/bin/pip install -r requirements.txt
  args:
    chdir: '{{ osp_src_dir }}'

- name: Install the package
  command: env/bin/python setup.py develop
  args:
    chdir: '{{ osp_src_dir }}'
