---

- name: Push the boto credentials
  template:
    src: boto.cfg.j2
    dest: /etc/boto.cfg

- name: Get server IP address
  register: scheduler
  ec2_remote_facts:
    region: '{{ ec2_region }}'
    filters:
      instance-state-name: running
      'tag:osp': cluster-scheduler

- name: Set the broker variable
  set_fact:
    osp_scheduler_host: >-
      {{ scheduler.instances[0].private_dns_name }}
